CREATE DATABASE ConnectPlus

CREATE TABLE TipoContato
(
IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Contato
(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) NOT NULL,
Imagem VARCHAR(100),
FormaContato VARCHAR(256) UNIQUE NOT NULL,
IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);

SELECT * FROM Contato